//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHY.EF.Admin.users
{


    public partial class user_list
    {
        protected global::System.Web.UI.WebControls.GridView usersView;

        protected global::System.Web.UI.WebControls.HiddenField infoCount;

        protected global::System.Web.UI.WebControls.HiddenField pageSize;

        protected global::System.Web.UI.WebControls.HiddenField pageIndex;

        protected global::System.Web.UI.WebControls.TextBox userName;
    }
}
